VERSION = "3.3.0"
APP_NAME = "ORBAS"

CLOUD_SYNC_URL = "https://app.orbas.com.au/api/sync"
LICENSE_VALIDATE_URL = "https://app.orbas.com.au/api/license/validate"
# Fixed product identifier expected by the ORBAS licence-activation endpoint.
PRODUCT_CODE = "ORBAS_EXTRACTOR"

JURISDICTIONS = [
    ("NSW", "New South Wales"),
    ("VIC", "Victoria"),
    ("QLD", "Queensland"),
    ("SA", "South Australia"),
    ("WA", "Western Australia"),
    ("TAS", "Tasmania"),
    ("ACT", "Australian Capital Territory"),
    ("NT", "Northern Territory"),
]

REPORT_TYPES = [
    ("auto", "Auto Detect"),
    ("move_in", "Move In Report"),
    ("move_out", "Move Out Report"),
    ("combined", "Combined Move In and Move Out Report"),
]

NSW_ROOMS = {
    "ENTRANCE/HALL": [
        "front door/screen door/security door",
        "walls/picture hooks",
        "doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points/door bell",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "LOUNGE ROOM": [
        "walls/picture hooks",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "DINING ROOM": [
        "walls/picture hooks",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "KITCHEN": [
        "walls/picture hooks",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "cupboards/drawers",
        "bench tops/tiling",
        "sink/taps/disposal unit",
        "stove top/hot plates",
        "oven/griller",
        "exhaust fan/range hood",
        "dishwasher",
        "other",
    ],
    "BEDROOM 1": [
        "walls/picture hooks",
        "built-in wardrobe/shelves",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "ENSUITE": [
        "walls/tiles",
        "floor tiles/floor coverings",
        "doors/doorway frame",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "bath/taps",
        "shower/screen/taps",
        "wash basin/taps",
        "mirror/cabinet/vanity",
        "towel rails",
        "toilet/cistern/seat",
        "toilet roll holder",
        "heating/exhaust fan/vent",
        "other",
    ],
    "BEDROOM 2": [
        "walls/picture hooks",
        "built-in wardrobe/shelves",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "BEDROOM 3": [
        "walls/picture hooks",
        "built-in wardrobe/shelves",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "BATHROOM": [
        "walls/tiles",
        "floor tiles/floor coverings",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "bath/taps",
        "shower/screen/taps",
        "wash basin/taps",
        "mirror/cabinet/vanity",
        "towel rails",
        "toilet/cistern/seat",
        "toilet roll holder",
        "heating/exhaust fan/vent",
        "other",
    ],
    "LAUNDRY": [
        "walls/tiles",
        "floor tiles/floor coverings",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "washing machine/taps",
        "exhaust fan/vent",
        "washing tub",
        "dryer",
        "other",
    ],
    "SECURITY/SAFETY": [
        "external door locks",
        "window locks",
        "keys/other security devices",
        "security/alarm system",
        "smoke alarms",
        "electrical safety switch",
        "other",
    ],
    "GENERAL": [
        "heating/air conditioning",
        "staircase/handrails",
        "external television antenna/tv points",
        "balcony/porch/deck",
        "swimming pool",
        "swimming pool fence/gate",
        "gates/fences",
        "grounds/garden",
        "garden hose/fittings",
        "watering system",
        "lawns/edges",
        "letter box/street number",
        "water tanks/septic tanks",
        "garbage bins",
        "paving/driveways",
        "clothesline",
        "garage/carport/storeroom",
        "garden shed",
        "hot water system",
        "gutters/downpipe",
        "other",
    ],
}

ACT_ROOMS = {
    "KITCHEN": [
        "stove top", "griller", "oven", "sink/disposal unit",
        "cupboards/drawers", "bench tops", "exhaust fan/vent",
        "floor/covering", "blinds/curtains", "walls/doors",
        "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "dish washer", "other",
    ],
    "BATHROOM": [
        "bath/spa", "basin/vanity", "shower recess",
        "shower screen/curtain", "mirror", "towel rail/soap holder",
        "exhaust fan/vent", "floor covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoint/switches", "shower head/rose", "other",
    ],
    "TOILET": [
        "bowl", "seat", "cistern", "exhaust fan/vent",
        "floor/covering", "blinds/curtains", "walls/doors",
        "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "LAUNDRY": [
        "trough", "cupboards", "exhaust fan/vent",
        "floor/covering", "blinds/curtains", "walls/doors",
        "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "BEDROOM 1": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "ENSUITE": [
        "basin/vanity/mirror", "shower recess", "shower screen/curtain",
        "towel rail/soap holder", "toilet bowl", "toilet seat",
        "cistern", "exhaust fan/vent", "floor/covering",
        "blinds/curtains", "walls/doors", "windows/screens",
        "shower head/rose", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "BEDROOM 2": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "BEDROOM 3": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "LOUNGE ROOM": [
        "heating system", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "OTHER ROOM 1": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "OTHER ROOM 2": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "EXTERIOR": [
        "letterbox", "external awnings", "security/screen doors",
        "concrete footpaths", "garden (front)", "lawn (front)",
        "garden (back)", "lawn (back)", "garden hose/fittings",
        "watering system", "driveway", "television antenna",
        "water softener", "clothesline", "garbage bin", "gutters", "other",
    ],
    "GARAGE/CARPORT": [
        "floor", "walls/doors", "windows/screens", "shelves",
        "ceiling/light fittings", "powerpoints/switches", "other",
    ],
    "SHED": [
        "floor", "walls/doors", "windows/screens", "shelves",
        "ceiling/light fittings", "powerpoints/switches", "other",
    ],
    "GENERAL": [
        "smoke detectors", "security system", "remote controls",
        "roller shutters", "other",
    ],
}

QLD_ROOMS = {
    "ENTRY": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings", "power points",
    ],
    "LOUNGE ROOM": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "tv/power points", "air conditioner",
    ],
    "FAMILY ROOM": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "tv/power points", "air conditioner",
    ],
    "KITCHEN/MEALS": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "cupboards/drawers", "bench tops/tiling",
        "sink/disposal unit/taps", "stove top", "oven/griller",
        "exhaust fan/rangehood", "dishwasher", "power points",
    ],
    "DINING ROOM": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "tv/power points", "air conditioner",
    ],
    "BEDROOM 1": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "wardrobe/drawers/shelves", "power points",
        "air conditioner", "smoke alarms",
    ],
    "ENSUITE": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "bath/shower/shower screen", "wash basin/vanity",
        "mirror/cabinet", "towel rails", "toilet",
        "power points", "exhaust fan",
    ],
    "BEDROOM 2": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "wardrobe/drawers/shelves", "power points",
        "air conditioner", "smoke alarms",
    ],
    "BEDROOM 3": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "wardrobe/drawers/shelves", "power points",
        "air conditioner", "smoke alarms",
    ],
    "BEDROOM 4": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "wardrobe/drawers/shelves", "power points",
        "air conditioner", "smoke alarms",
    ],
    "BATHROOM": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "bath", "shower/shower screen", "wash basin/vanity",
        "mirror/cabinet", "towel rails", "power points",
        "exhaust fan", "toilet",
    ],
    "TOILET": [
        "doors/walls/ceiling", "cistern", "light fittings", "exhaust fan",
    ],
    "LAUNDRY": [
        "doors/walls/ceiling", "windows/screens", "blinds/curtains",
        "fans/light fittings", "floor/floor coverings",
        "wash tubs", "washing machine/dryer", "power points",
    ],
    "GENERAL": [
        "smoke alarms", "security devices",
        "electrical safety switches", "hot water system",
        "keys/locks/remotes", "staircases/railings",
        "wheelie & recycle bins", "pool/equipment",
        "street number/letter box", "external walls",
        "balcony/porch/deck", "awning/gutters",
        "paving/pergola", "garage/car port/storeroom",
        "garden shed", "gates/fences", "grounds/garden",
        "external taps/hose", "clothes line",
        "solar panels", "paths/driveway",
    ],
}

VIC_ROOMS = {
    "ENTRANCE HALL": [
        "front door", "front door locks", "screen door", "walls",
        "picture hooks", "windows", "screens", "window locks",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "built in cupboard", "other",
    ],
    "LOUNGE ROOM": [
        "doors", "walls", "picture hooks", "windows", "screens",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points",
        "tv connection", "telephone connection", "other",
    ],
    "KITCHEN / MEALS": [
        "doors", "walls", "picture hooks", "windows", "screens",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "cupboards/drawers",
        "bench tops", "tiling", "sink", "taps",
        "hot plates/stove top", "oven/grill",
        "exhaust fan/rangehood", "dishwasher", "other",
    ],
    "BEDROOM 1": [
        "doors", "walls", "picture hooks", "wardrobe/drawers",
        "windows", "screens", "window locks",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "other",
    ],
    "ENSUITE": [
        "doors", "walls", "picture hooks", "windows", "screens",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "bath", "shower",
        "shower screen", "basin", "taps", "vanity unit",
        "mirror/cabinet", "towel rails", "toilet",
        "cistern", "toilet roll holder",
        "exhaust fan/vent", "other",
    ],
    "BEDROOM 2": [
        "doors", "walls", "picture hooks", "wardrobe/drawers",
        "windows", "screens", "window locks",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "other",
    ],
    "BEDROOM 3": [
        "doors", "walls", "picture hooks", "wardrobe/drawers",
        "windows", "screens", "window locks",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "other",
    ],
    "BEDROOM 4": [
        "doors", "walls", "picture hooks", "wardrobe/drawers",
        "windows", "screens", "window locks",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "other",
    ],
    "MAIN BATHROOM": [
        "doors", "walls", "windows", "screens",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "bath", "shower",
        "shower screen", "basin", "taps", "vanity unit",
        "mirror/cabinet", "towel rails", "toilet",
        "cistern", "toilet roll holder",
        "exhaust fan/vent", "other",
    ],
    "TOILET": [
        "door", "walls", "ceiling", "light fittings",
        "floor coverings", "toilet", "cistern",
        "toilet roll holder", "exhaust fan/vent", "other",
    ],
    "LAUNDRY": [
        "doors", "walls", "windows", "screens",
        "blinds/curtains", "ceiling", "light fittings",
        "floor coverings", "power points", "trough/tub",
        "taps", "cupboards", "other",
    ],
    "GENERAL – INSIDE": [
        "heating/air conditioning", "staircase/handrails",
        "smoke alarms", "safety switch", "other",
    ],
    "BALCONY/PORCH": [
        "doors", "walls", "ceiling", "light fittings",
        "floor coverings", "railings", "other",
    ],
    "GENERAL – OUTSIDE": [
        "external tv antenna/tv points", "letter box",
        "garden/grounds", "lawns/edges", "garden hose/fittings",
        "clothesline", "fences/gates", "paths/driveway",
        "garage/car port", "pool fence and gate",
        "pool/spa equipment", "garden shed",
        "hot water system", "gutters/downpipe", "other",
    ],
}

TAS_ROOMS = {
    "ENTRANCE/HALL": [
        "front door/screen door/security door",
        "walls/picture hooks", "doorway frames",
        "windows/screens", "ceilings/light fittings",
        "blinds/curtains", "lights/power points",
        "skirting boards", "floor coverings", "other",
    ],
    "LOUNGE ROOM": [
        "walls/picture hooks", "doors/doorway frames",
        "windows/screens", "ceiling/light fittings",
        "blinds/curtains", "lights/power points",
        "skirting boards", "floor coverings", "other",
    ],
    "DINING ROOM": [
        "walls/picture hooks", "doors/doorway frames",
        "windows/screens", "ceiling/light fittings",
        "blinds/curtains", "lights/power points",
        "skirting boards", "floor coverings", "other",
    ],
    "KITCHEN": [
        "walls/picture hooks", "doors/doorway frames",
        "windows/screens", "ceiling/light fittings",
        "blinds/curtains", "lights/power points",
        "skirting boards", "floor coverings",
        "cupboards/drawers", "bench tops/tiling",
        "sinks/taps", "stove tops/hot plates",
        "oven/griller", "exhaust fan/range hood",
        "dishwasher", "other",
    ],
    "BEDROOM 1": [
        "walls/picture hooks", "built-in wardrobe/shelves",
        "doors/doorway frames", "windows/screens",
        "ceiling/light fittings", "blinds/curtains",
        "lights/power points", "skirting boards",
        "floor coverings", "other",
    ],
    "ENSUITE": [
        "walls/tiles", "floor tiles/floor coverings",
        "doors/doorway frame", "windows/screens",
        "ceiling/light fittings", "blinds/curtains",
        "lights/power points", "baths/taps",
        "shower/screen/taps", "wash basin/taps",
        "mirror/cabinet/vanity", "towel rails",
        "toilet/cistern/seat", "toilet roll holder",
        "heating/exhaust fan/vent", "other",
    ],
    "BEDROOM 2": [
        "walls/picture hooks", "built-in wardrobe/shelves",
        "doors/doorway frames", "windows/screens",
        "ceiling/light fittings", "blinds/curtains",
        "lights/power points", "skirting boards",
        "floor coverings", "other",
    ],
    "BEDROOM 3": [
        "walls/picture hooks", "built-in wardrobe/shelves",
        "doors/doorway frames", "windows/screens",
        "ceiling/light fittings", "blinds/curtains",
        "lights/power points", "skirting boards",
        "floor coverings", "other",
    ],
    "BATHROOM": [
        "walls/tiles", "floor tiles/floor coverings",
        "doors/doorway frame", "windows/screens",
        "ceiling/light fittings", "blinds/curtains",
        "lights/power points", "baths/taps",
        "shower/screen/taps", "wash basin/taps",
        "mirror/cabinet/vanity", "towel rails",
        "toilet/cistern/seat", "toilet roll holder",
        "heating/exhaust fan/vent", "other",
    ],
    "LAUNDRY": [
        "walls/tiles", "floor tiles/floor coverings",
        "doors/doorway frame", "windows/screens",
        "ceiling/light fittings", "blinds/curtains",
        "lights/power points", "washing machine taps",
        "exhaust fan/vent", "washing tub",
        "dryer", "other",
    ],
    "SECURITY/SAFETY": [
        "external door locks", "window locks",
        "keys/other security devices", "smoke alarms",
        "residual current device (rcd)", "other",
    ],
    "GENERAL": [
        "heating/air conditioning", "staircase/handrails",
        "external tv antenna/tv points",
        "balcony/porch/deck", "hot water system",
        "gates/fences", "garden beds", "lawns/edges",
        "garage/carport/storeroom", "garage/roller doors",
        "garden hose/fittings", "clothesline",
        "letter box/street number", "gutters/downpipe",
        "swimming pool", "other",
    ],
}

SA_ROOMS = {
    "KITCHEN": [
        "stove top", "griller", "oven", "sink/disposal unit",
        "cupboards/drawers", "bench tops", "exhaust fan/vent",
        "floor/covering", "blinds/curtains", "walls/doors",
        "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "dish washer", "other",
    ],
    "BATHROOM": [
        "bath/spa", "basin/vanity", "shower recess",
        "shower screen/curtain", "mirror", "towel rail/soap holder",
        "exhaust fan/vent", "floor covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoint/switches", "shower head/rose", "other",
    ],
    "TOILET": [
        "bowl", "seat", "cistern", "exhaust fan/vent",
        "floor/covering", "blinds/curtains", "walls/doors",
        "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "LAUNDRY": [
        "trough", "cupboard/s", "exhaust fan/vent",
        "floor/covering", "blinds/curtains", "walls/doors",
        "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "BEDROOM 1": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "ENSUITE": [
        "basin/vanity/mirror", "shower recess", "shower screen/curtain",
        "towel rail/soap holder", "toilet bowl", "toilet seat",
        "cistern", "exhaust fan/vent", "floor/covering",
        "blinds/curtains", "walls/doors", "windows/screens",
        "shower head/rose", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "BEDROOM 2": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "BEDROOM 3": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "LOUNGE ROOM": [
        "heating system", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "OTHER ROOM 1": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "OTHER ROOM 2": [
        "built-ins", "floor/covering", "blinds/curtains",
        "walls/doors", "windows/screens", "ceiling/light fittings",
        "powerpoints/switches", "other",
    ],
    "EXTERIOR": [
        "letterbox", "external awnings", "security/screen doors",
        "concrete footpaths", "garden (front)", "lawn (front)",
        "garden (back)", "lawn (back)", "garden hose/fittings",
        "watering system", "driveway", "television antenna",
        "water softener", "clothesline", "garbage bin", "gutters", "other",
    ],
    "GARAGE/CARPORT": [
        "floor", "walls/doors", "windows/screens", "shelves",
        "ceiling/light fittings", "powerpoints/switches", "other",
    ],
    "SHED": [
        "floor", "walls/doors", "windows/screens", "shelves",
        "ceiling/light fittings", "powerpoints/switches", "other",
    ],
    "GENERAL": [
        "smoke detectors", "security system", "remote controls",
        "roller shutters", "other",
    ],
}

WA_ROOMS = {
    "ENTRY": [
        "front door", "screen door/security door",
        "walls/picture hooks", "windows/screens",
        "ceiling", "light fittings", "blinds/curtains",
        "power points", "floorcoverings",
    ],
    "LOUNGE ROOM": [
        "doors/doorway frames", "walls/picture hooks",
        "windows/screens", "ceiling", "light fittings",
        "blinds/curtains", "tv/power points", "floorcoverings",
    ],
    "DINING ROOM": [
        "doors/doorway frames", "walls/picture hooks",
        "windows/screens", "ceiling", "light fittings",
        "blinds/curtains", "power points", "floorcoverings",
    ],
    "KITCHEN": [
        "doors/doorway frames", "walls/picture hooks",
        "windows/screens", "ceiling", "light fittings",
        "blinds/curtains", "power points", "floorcoverings",
        "cupboards/drawers", "bench tops/tiling",
        "sink/taps", "stove top/hot plates",
        "oven/griller", "exhaust fan/range hood",
    ],
    "EACH BEDROOM": [
        "doors/doorway frames", "walls/picture hooks",
        "windows/screens", "ceiling", "light fittings",
        "blinds/curtains", "power points", "floorcoverings",
    ],
    "EACH BATHROOM": [
        "doors/doorway frames", "walls/tiles",
        "windows/screens", "ceiling", "light fittings",
        "blinds/curtains", "power points", "floorcoverings",
        "bath/taps", "shower/screen/taps", "wash basin/taps",
        "mirror/cabinet/vanity", "towel rails",
        "toilet/cistern/seat", "toilet roll holder",
        "heating/exhaust fan/vent",
    ],
    "LAUNDRY": [
        "doors/doorway frames", "walls/tiles",
        "windows/screens", "ceiling", "light fittings",
        "blinds/curtains", "power points", "floorcoverings",
        "washing machine taps", "exhaust fan/vent", "washing tub",
    ],
    "SECURITY/ SAFETY": [
        "smoke alarms", "electrical safety switch",
        "keys/other opening devices",
    ],
    "GENERAL": [
        "garden", "lawn/edges", "letterbox/street number",
        "water tanks/septic tanks", "garbage bins",
        "paving/driveways", "clothesline",
        "garage/carport/storeroom", "garden shed",
        "hot water system", "gutters/downpipes",
    ],
}

ROOM_CONFIGS = {
    "NSW": NSW_ROOMS,
    "ACT": ACT_ROOMS,
    "QLD": QLD_ROOMS,
    "VIC": VIC_ROOMS,
    "TAS": TAS_ROOMS,
    "SA": SA_ROOMS,
    "WA": WA_ROOMS,
}

REPORT_TYPE_KEYWORDS = {
    "move_in": [
        "move in", "move-in", "commencement", "start of tenancy",
        "ingoing", "entry", "beginning of lease",
    ],
    "move_out": [
        "move out", "move-out", "end of tenancy", "vacating",
        "outgoing", "exit", "termination of lease",
    ],
    "combined": [
        "condition report", "start of tenancy", "end of tenancy",
    ],
}
