VERSION = "1.0.0"
APP_NAME = "PDF Condition Report Extractor"

JURISDICTIONS = [
    ("NSW", "New South Wales"),
    ("VIC", "Victoria"),
    ("QLD", "Queensland"),
    ("SA", "South Australia"),
    ("WA", "Western Australia"),
    ("TAS", "Tasmania"),
    ("ACT", "Australian Capital Territory"),
    ("NT", "Northern Territory"),
]

REPORT_TYPES = [
    ("auto", "Auto Detect"),
    ("move_in", "Move In Report"),
    ("move_out", "Move Out Report"),
    ("combined", "Combined Move In and Move Out Report"),
]

NSW_ROOMS = {
    "ENTRANCE/HALL": [
        "front door/screen door/security door",
        "walls/picture hooks",
        "doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points/door bell",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "LOUNGE ROOM": [
        "walls/picture hooks",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "DINING ROOM": [
        "walls/picture hooks",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "KITCHEN": [
        "walls/picture hooks",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "cupboards/drawers",
        "bench tops/tiling",
        "sink/taps/disposal unit",
        "stove top/hot plates",
        "oven/griller",
        "exhaust fan/range hood",
        "dishwasher",
        "other",
    ],
    "BEDROOM 1": [
        "walls/picture hooks",
        "built-in wardrobe/shelves",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "ENSUITE": [
        "walls/tiles",
        "floor tiles/floor coverings",
        "doors/doorway frame",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "bath/taps",
        "shower/screen/taps",
        "wash basin/taps",
        "mirror/cabinet/vanity",
        "towel rails",
        "toilet/cistern/seat",
        "toilet roll holder",
        "heating/exhaust fan/vent",
        "other",
    ],
    "BEDROOM 2": [
        "walls/picture hooks",
        "built-in wardrobe/shelves",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "BEDROOM 3": [
        "walls/picture hooks",
        "built-in wardrobe/shelves",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "skirting boards",
        "floor coverings",
        "other",
    ],
    "BATHROOM": [
        "walls/tiles",
        "floor tiles/floor coverings",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "bath/taps",
        "shower/screen/taps",
        "wash basin/taps",
        "mirror/cabinet/vanity",
        "towel rails",
        "toilet/cistern/seat",
        "toilet roll holder",
        "heating/exhaust fan/vent",
        "other",
    ],
    "LAUNDRY": [
        "walls/tiles",
        "floor tiles/floor coverings",
        "doors/doorway frames",
        "windows/screens/window safety devices",
        "ceiling/light fittings",
        "blinds/curtains",
        "lights/power points",
        "washing machine/taps",
        "exhaust fan/vent",
        "washing tub",
        "dryer",
        "other",
    ],
    "SECURITY/SAFETY": [
        "external door locks",
        "window locks",
        "keys/other security devices",
        "security/alarm system",
        "smoke alarms",
        "electrical safety switch",
        "other",
    ],
    "GENERAL": [
        "heating/air conditioning",
        "staircase/handrails",
        "external television antenna/tv points",
        "balcony/porch/deck",
        "swimming pool",
        "swimming pool fence/gate",
        "gates/fences",
        "grounds/garden",
        "garden hose/fittings",
        "watering system",
        "lawns/edges",
        "letter box/street number",
        "water tanks/septic tanks",
        "garbage bins",
        "paving/driveways",
        "clothesline",
        "garage/carport/storeroom",
        "garden shed",
        "hot water system",
        "gutters/downpipe",
        "other",
    ],
}

ROOM_CONFIGS = {
    "NSW": NSW_ROOMS,
}

REPORT_TYPE_KEYWORDS = {
    "move_in": [
        "move in", "move-in", "commencement", "start of tenancy",
        "ingoing", "entry", "beginning of lease",
    ],
    "move_out": [
        "move out", "move-out", "end of tenancy", "vacating",
        "outgoing", "exit", "termination of lease",
    ],
    "combined": [
        "condition report", "start of tenancy", "end of tenancy",
    ],
}
